services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    secrets:
      - firebase_credentials
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgres://postgres:password@db:5432/customers
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    env_file:
      - .env.local
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:17
    restart: always
    user: postgres
    secrets:
      - db_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: customers
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:


secrets:
  db_password:
    file: ./secrets/db-password.txt
  firebase_credentials:
    file: ./secrets/firebase-private-key.json
