services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgres://postgres:password@db:5432/customers
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    env_file:
      - .env.local
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: sh ./scripts/start.dev.sh

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customers
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: 